<?php

return [
'Asmoria\Core\Configuration' => ROOT_DIR . '/Core/Configuration.php',
'Asmoria\Core\Controller' => ROOT_DIR . '/Core/Controller.php',
'Asmoria\Core\Core' => ROOT_DIR . '/Core/Core.php',
'Asmoria\Core\Model' => ROOT_DIR . '/Core/Model.php',
'Asmoria\Core\Route' => ROOT_DIR . '/Core/Route.php',
'Asmoria\Core\View' => ROOT_DIR . '/Core/View.php',
'Asmoria\Core\classes' => ROOT_DIR . '/Core/classes.php',
'Asmoria\Modules\Administration\AdministrationController' => ROOT_DIR . '/Modules/Administration/AdministrationController.php',
'Asmoria\Modules\Administration\Models\AclRolesModel' => ROOT_DIR . '/Modules/Administration/Models/AclRolesModel.php',
'Asmoria\Modules\Administration\Models\AclUsersModel' => ROOT_DIR . '/Modules/Administration/Models/AclUsersModel.php',
'Asmoria\Modules\Handler\HandlerController' => ROOT_DIR . '/Modules/Handler/HandlerController.php',
'Asmoria\Modules\Main\MainController' => ROOT_DIR . '/Modules/Main/MainController.php',
'Asmoria\Modules\Profiler\CabinetController' => ROOT_DIR . '/Modules/Profiler/CabinetController.php',
'Asmoria\Modules\Profiler\Models\ProfileModel' => ROOT_DIR . '/Modules/Profiler/Models/ProfileModel.php',
'Asmoria\Modules\Profiler\ProfilerController' => ROOT_DIR . '/Modules/Profiler/ProfilerController.php',
'Asmoria\Modules\Socket\Handler' => ROOT_DIR . '/Modules/Socket/Handler.php',
'Asmoria\Modules\Socket\Master' => ROOT_DIR . '/Modules/Socket/Master.php',
'Asmoria\Modules\Socket\Server' => ROOT_DIR . '/Modules/Socket/Server.php',
'Asmoria\Modules\Socket\SocketController' => ROOT_DIR . '/Modules/Socket/SocketController.php',
'Asmoria\Modules\Socket\Worker' => ROOT_DIR . '/Modules/Socket/Worker.php',
'Asmoria\index' => ROOT_DIR . '/index.php',
];